create table "public"."lesson" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "title" text,
    "description" text
);


alter table "public"."lesson" enable row level security;

CREATE UNIQUE INDEX lesson_pkey ON public.lesson USING btree (id);

alter table "public"."lesson" add constraint "lesson_pkey" PRIMARY KEY using index "lesson_pkey";


